In [9]:
# scratch pad
import numpy as np

In [2]:
i = 0
waitTime = 10 
transition_list = []
transition_list.append({
    'index': i,
    'waitTime': waitTime
})

In [4]:
# generator example
def simple_gen(n):
    i = 0
    while i < n:
        yield i
        i += 1

In [7]:
for x in simple_gen(10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [10]:
y = np.zeros(5)
order = np.argsort(y)

In [13]:
order,y

(array([0, 1, 2, 3, 4], dtype=int64), array([0., 0., 0., 0., 0.]))

In [15]:
x = np.zeros((5,6))
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
x[:] = x[order]
y[:] = y[order]

In [20]:
x,y

(array([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]), array([0., 0., 0., 0., 0.]))

In [24]:
x0 = np.mean(x[:-1],axis=0)
x0

array([0., 0., 0., 0., 0., 0.])

In [23]:
x[-1]

array([0., 0., 0., 0., 0., 0.])

In [27]:
a = [(yield x) for x in np.linspace(0,10,100)]

<generator object <listcomp> at 0x000001516185B2A0>